version: '2.1'
services:

  nginx-proxy:
    image: nginx-proxy:latest
   hostname: mydomain.com
    user: root
    ports:
      - 80:80
      - 443:443
      - 81:81
    privileged: true
    networks:
      - my_app

networks:
  my_app:
    driver: "bridge"
